# Crowd Analysis System Configuration
# This file provides a modern YAML-based configuration format

video:
  video_cap: "video/7.mp4"          # Video file path or camera index (0, 1, etc.)
  is_cam: false                     # Set to true for live camera feed
  cam_approx_fps: 3                 # Approximate processing FPS for camera mode
  high_cam: true                    # Camera position (affects distance calculation)
  start_time: "2020-11-05T00:00:00" # Video start timestamp (ISO format)

yolo:
  weights_path: "YOLOv4-tiny/yolov4-tiny.weights"  # Path to YOLO weights
  config_path: "YOLOv4-tiny/yolov4-tiny.cfg"       # Path to YOLO config
  min_conf: 0.3                     # Minimum detection confidence (0.0-1.0)
  nms_thresh: 0.2                   # Non-maximum suppression threshold (0.0-1.0)

detection:
  show_processing_output: true      # Display video output during processing
  show_detect: true                 # Show detection bounding boxes
  show_tracking_id: true            # Show tracking IDs on detections
  frame_size: 1080                  # Frame width for processing (480-1920)
  data_record: true                 # Record processing data to files
  data_record_rate: 5               # Data recording rate (per second)

social_distance:
  enabled: true                     # Enable social distance monitoring
  show_violation_count: true        # Display violation count on screen
  social_distance: 50               # Minimum distance in pixels

restricted_entry:
  enabled: false                    # Enable restricted entry monitoring
  start_time: "09:00:00"           # Restriction start time (HH:MM:SS)
  end_time: "17:00:00"             # Restriction end time (HH:MM:SS)

abnormal_activity:
  enabled: true                     # Enable abnormal activity detection
  min_people: 5                     # Minimum people count to check abnormal activity
  energy_threshold: 1866            # Energy level threshold for abnormal activity
  activity_threshold: 0.66          # Ratio threshold for abnormal activity (0.0-1.0)

tracking:
  max_age: 3                        # Maximum age before removing tracks (seconds)
  max_cosine_distance: 0.7          # Maximum cosine distance for matching
  nn_budget: null                   # Neural network budget (null for unlimited)
